### ISSUE TITLE
Missing version field

### ISSUE THREAD

**Issue by thewh1teagle** [katyo/publish-crates#668]
I'm using this github action on my open source repo.
It worked well for few months and then I got this error:
```rust
Error: Missing dependency 'rookie' version field
```
I do have version in my `rookie` package. I don't know why it doesn't find it.
Also, when I run `cargo publish` in my PC it works.

[github.com/thewh1teagle/rookie](https://github.com/thewh1teagle/rookie)

[workflow.yaml](https://github.com/thewh1teagle/rookie/blob/main/.github/workflows/CRATE.yml)

[actions/runs/7281768607](https://github.com/thewh1teagle/rookie/actions/runs/7281768607/job/19842926963)

**Comment by katyo** [comment]
@thewh1teagle This is known issue. Currently you should specify concrete version for all you local dependencies. I working on removing this restriction. May be I publish new version soon.

**Comment by thewh1teagle** [comment]
Can you also improve the error log?
It took me a long time to investigate it, until I gave up and posted here

**Comment by thewh1teagle** [comment]
Also I already have version for each package:
https://github.com/thewh1teagle/rookie/blob/main/rookie-rs/Cargo.toml

**Comment by katyo** [comment]
@thewh1teagle I mean the version requirements. Actually you haven't specified it for each local dependency. For ex.:

https://github.com/thewh1teagle/rookie/blob/main/cli/Cargo.toml#L12

**Comment by katyo** [comment]
@thewh1teagle Seems I fixed this issue. Could you test latest v2 release?

**Comment by thewh1teagle** [comment]
It may still happens 
[runs/8775776707/job/24078500429](https://github.com/thewh1teagle/rookie/actions/runs/8775776707/job/24078500429)
[publish-crate.yml](https://github.com/thewh1teagle/rookie/blob/main/.github/workflows/publish-crate.yml)

**Comment by katyo** [comment]
@thewh1teagle It because cargo doesn't check your repo for changes in packages since last published version.
